addresses:
  "75a756724565f5b0be4fa40c671ce2a647e2edfa12a8f6737226e2f32cf7b10b": "127.0.0.1:9000"
  "a00c4726dcee7e2e885278dc70c8ea1e9de30cd12c25f383303f9713f414f071": "127.0.0.1:9001"
  "2ac1b57b44ec16fdf46b9816e10c428d64ad5cb92514b4bb89a1f8bdaf07b279": "127.0.0.1:9002"
  "cc2d203383d7246631802e62687e7245880d26108a177504789b836492927901": "127.0.0.1:9003"
