addresses:
  "edd0f6de342a1e6a7236d6244f23d83eedfcecd059a386c85055701498e77033": "127.0.0.1:9000"
  "478b8e507e0bb2b18c0f9e0824769e8562d10df9abe2e774896f82b4b4405266": "127.0.0.1:9001"
  "5925ba86e2189444a6c3b437b25d2ef35daecd1abf82c5fb36060f9fc0af428c": "127.0.0.1:9002"
  "ec8924090e507c2d8371d2fb0bf965d553e6e5756aeec6c274df3801cf2b49b9": "127.0.0.1:9003"
