global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "simulator"
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: "auth"
    metrics_path: /metrics/prometheus
    static_configs:
      - targets: ["host.docker.internal:4000"]
