addresses:
  "fba404e8b4b9d34c1069d848d94778417268045e9c37031dd90cf59418048e9c": "127.0.0.1:9000" # node0 bootstrapper (local)
  "bd91297c02e14759b34f0aced8a98308105957f275dd64816b7c7076eadfce63": "127.0.0.1:9001" # node1
  "25b57eddbada8c268ad7568dc7d2f128b717ce11c30cd17896b6c0b145940b9a": "127.0.0.1:9002" # node2
  "c0bc76af7398610edd9de16dae0466c63ee4946eff9490246e59d6bb4d40c854": "127.0.0.1:9003" # node3
